export { default as SpecializedQuestion } from './SpecializedQuestionSection';
export { default as ProcessDetailsSection } from './ProcessDetailsSection';
export { default as ProcessesSection } from './ProcessesSection';
export { default as TeamSection } from './TeamSection';
export { default as TechnologySection } from './TechnologySection';
export { default as ChallengesSection } from './ChallengesSection';
export { default as GoalsSection } from './GoalsSection';
export { default as LandingSection } from './LandingSection';
export { default as ResultsSection } from './ResultsSection';
